### ISSUE TITLE
InaccessibleObjectException during build when generating sources

### ISSUE THREAD

**Issue by axor-mst** [Sipkab/ruby-hunter#3]
Hello,

Trying to build the game but I keep getting [an error](https://github.com/Sipkab/ruby-hunter/files/6341321/build-error.txt). Commands used are as follows:
`java -jar saker.build.jar -bd build install sipka.rubyhunter/saker.build` 
then either (changing the platforname to "win32" in saker.build):
`java -jar saker.build.jar -bd build resources`
or just:
`java -jar saker.build.jar -bd build export_win32`
Am I missing any steps or dependencies?

**Comment by Sipkab** [comment]
Hi,

I've fixed this build error in commit df1eaf633cd10e911c0bb0743b6ef80a41bd3c1d. You will need to run 
`java -jar saker.build.jar -bd build install sipka.rubyhunter/saker.build` 
again.

Also note that you don't need to run the `resources` build target, simply running:
`java -jar saker.build.jar -bd build export_win32`
should be fine.

**Comment by axor-mst** [comment]
Many thanks, it builds successfully now, and after installing XAudio from [this package](https://microsoft.com/en-us/download/details.aspx?id=35) I was able to run it.

The reason I was trying to build only the `resources` target was #4.
