### ISSUE TITLE
Level conversion - from Sapphire Yours to Ruby Hunter format

### ISSUE THREAD

**Issue by axor-mst** [Sipkab/ruby-hunter#4]
Hello,

I have a bunch of levels created back then in the original Sapphire Yours game, is there any way to convert them into the currently used format?

**Comment by Sipkab** [comment]
You can copy the levels into the directory `gameres/game_sapphire/levels/custom/`. Make sure that your level files have the extension `.sylev`.
After that you can build the project as specified in the README. Your added levels should appear in the level browser in-game. (You can also start typing the name of a level you're searching for while browsing, they will be filtered out.)

Let me know if you have any issues.

**Comment by axor-mst** [comment]
Thanks, works perfectly.
